# -*- coding: utf-8 -*-

from .base_spider import *
from ..items import listed_company


class stock_company_a_spider(csmar_base_spider):
    # fields
    name = 'stock_company_a_spider'

    space = relativedelta(years=1)

    def start_requests(self):
        start = date(1990, 12, 1)
        for item in super().start_requests(start, None):
            yield item

    def parse(self, response):
        col_data, json_data = super().parse(response)
        if json_data:
            for item in super().build_items(json_data, col_data, listed_company):
                yield item
            pass
        pass

    def build_query_set(self, start, stock_code=None):
        start_str = start.strftime('%Y-%m-%d')
        end_str = (start + self.space).strftime('%Y-%m-%d')
        return {
            "Tables": [
                {
                    "TbId": 698,
                    "Fields": [
                        {"DownCount": 35390, "Pid": 253, "Fldid": 10481, "Fldname": "Stkcd", "Showorder": 1,
                         "Replaceid": None, "Tbid": 698, "Datatypeid": 126, "Langid": 0, "Unitid": 0, "Mlangid": 12030,
                         "Kid": 1, "Typename": "Nvarchar", "Length": 6, "Accuracy": 0, "Mergerdatatype": "C(6)",
                         "Title": "证券代码", "Description": "上海A股以上交所公布的证券代码为准，深圳A股以深交所公布的证券代码为准。", "Langtypeid": 1,
                         "TBTitle": "公司基本情况表", "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 1, "UnitTitle": "没有单位",
                         "Keytype": 1, "UnitValue": 0, "Mergerunit": "没有单位", "Iscode": 0
                         },
                        {"DownCount": 9569, "Pid": 253, "Fldid": 10482, "Fldname": "Crcd", "Showorder": 2,
                         "Replaceid": None, "Tbid": 698, "Datatypeid": 126, "Langid": 0, "Unitid": 0, "Mlangid": 12031,
                         "Kid": 0, "Typename": "Nvarchar", "Length": 6, "Accuracy": 0, "Mergerdatatype": "C(6)",
                         "Title": "A、B股交叉码", "Description": "指该公司发行的其他证券代码，以交易所公布的证券简称为准。None：指该公司只发行了A股。",
                         "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 0,
                         "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0,
                         "Mergerunit": "没有单位", "Iscode": 0},
                        {"DownCount": 20459, "Pid": 253, "Fldid": 10483, "Fldname": "Stknme", "Showorder": 3,
                         "Replaceid": None, "Tbid": 698, "Datatypeid": 136, "Langid": 0, "Unitid": 0, "Mlangid": 12032,
                         "Kid": 0, "Typename": "Nvarchar", "Length": 8, "Accuracy": 0, "Mergerdatatype": "C(8)",
                         "Title": "证券简称", "Description": "以交易所公布的证券简称为准。", "Langtypeid": 1, "TBTitle": "公司基本情况表",
                         "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0,
                         "Mergerunit": "没有单位", "Iscode": 0},
                        {"DownCount": 13153, "Pid": 253, "Fldid": 10486, "Fldname": "Indcd", "Showorder": 6,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 101, "Langid": 0, "Unitid": 0, "Mlangid": 12035, "Kid": 0,
                         "Typename": "Nvarchar", "Length": 4, "Accuracy": 0, "Mergerdatatype": "C(4)", "Title": "行业代码A",
                         "Description": "0001；0002；0003；0004；0005；0006。", "Langtypeid": 1, "TBTitle": "公司基本情况表",
                         "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0,
                         "Mergerunit": "没有单位", "Iscode": 0},
                        {"DownCount": 13409, "Pid": 253, "Fldid": 10487, "Fldname": "Indnme", "Showorder": 7,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 153, "Langid": 0, "Unitid": 0, "Mlangid": 12036, "Kid": 0,
                         "Typename": "Nvarchar", "Length": 50, "Accuracy": 0, "Mergerdatatype": "C(50)",
                         "Title": "行业名称A",
                         "Description": "0001=金融；0002=公用事业；0003=房地产；0004=综合；0005=工业；0006=商业。", "Langtypeid": 1,
                         "TBTitle": "公司基本情况表", "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "没有单位",
                         "Keytype": 0,
                         "UnitValue": 0, "Mergerunit": "没有单位", "Iscode": 1},
                        {"DownCount": 10897, "Pid": 253, "Fldid": 10492, "Fldname": "Listexg", "Showorder": 13,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 126, "Langid": 0, "Unitid": 0, "Mlangid": 12041, "Kid": 0,
                         "Typename": "Nvarchar", "Length": 6, "Accuracy": 0, "Mergerdatatype": "C(6)", "Title": "上市交易所",
                         "Description": "1=上海证券交易所，2＝深圳证券交易所。", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0,
                         "Mergerunit": "没有单位", "Iscode": 1},
                        {"DownCount": 15148, "Pid": 253, "Fldid": 10493, "Fldname": "Conme", "Showorder": 14,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 139, "Langid": 0, "Unitid": 0, "Mlangid": 12042, "Kid": 0,
                         "Typename": "Nvarchar", "Length": 80, "Accuracy": 0, "Mergerdatatype": "C(80)",
                         "Title": "公司名称",
                         "Description": "上市时的公司名称", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）",
                         "NodeID": 0, "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0, "Mergerunit": "没有单位",
                         "Iscode": 0},
                        {"DownCount": 6828, "Pid": 253, "Fldid": 10494, "Fldname": "Conmee", "Showorder": 15,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 41, "Langid": 0, "Unitid": 0, "Mlangid": 12043, "Kid": 0,
                         "Typename": "Nvarchar", "Length": 150, "Accuracy": 0, "Mergerdatatype": "C(150)",
                         "Title": "公司英文名称",
                         "Description": "上市时的公司英文名称", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）",
                         "NodeID": 0, "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0, "Mergerunit": "没有单位",
                         "Iscode": 0},
                        {"DownCount": 13817, "Pid": 253, "Fldid": 10495, "Fldname": "Estbdt", "Showorder": 16,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 55, "Langid": 0, "Unitid": 0, "Mlangid": 12044, "Kid": 0,
                         "Typename": "Datetime", "Length": 10, "Accuracy": 0, "Mergerdatatype": "D(10)",
                         "Title": "公司成立日期",
                         "Description": "以YYYY-MM-DD列示，部分缺少在相应位置上以00表示，如1993年12月某日表示为1993-12-00。", "Langtypeid": 1,
                         "TBTitle": "公司基本情况表", "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "没有单位",
                         "Keytype": 0,
                         "UnitValue": 0, "Mergerunit": "没有单位", "Iscode": 0},
                        {"DownCount": 9892, "Pid": 253, "Fldid": 10496, "Fldname": "Ipodt", "Showorder": 17,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 55, "Langid": 0, "Unitid": 0, "Mlangid": 12045, "Kid": 0,
                         "Typename": "Datetime", "Length": 10, "Accuracy": 0, "Mergerdatatype": "D(10)",
                         "Title": "首次招股日期",
                         "Description": "以YYYY-MM-DD列示，部分缺少在相应位置上以00表示，如1993年12月某日表示为1993-12-00。", "Langtypeid": 1,
                         "TBTitle": "公司基本情况表", "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "没有单位",
                         "Keytype": 0,
                         "UnitValue": 0, "Mergerunit": "没有单位", "Iscode": 0},
                        {"DownCount": 23919, "Pid": 253, "Fldid": 10497, "Fldname": "Listdt", "Showorder": 18,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 55, "Langid": 1, "Unitid": 0, "Mlangid": 12046, "Kid": 2,
                         "Typename": "Datetime", "Length": 10, "Accuracy": 0, "Mergerdatatype": "D(10)",
                         "Title": "公司上市日期",
                         "Description": "以YYYY-MM-DD列示，部分缺少在相应位置上以00表示，如1993年12月某日表示为1993-12-00。", "Langtypeid": 1,
                         "TBTitle": "公司基本情况表", "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "没有单位",
                         "Keytype": 2,
                         "UnitValue": 0, "Mergerunit": "没有单位", "Iscode": 0},
                        {"DownCount": 14042, "Pid": 253, "Fldid": 10498, "Fldname": "Regadd", "Showorder": 19,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 10, "Langid": 0, "Unitid": 0, "Mlangid": 12047, "Kid": 0,
                         "Typename": "Nvarchar", "Length": 60, "Accuracy": 0, "Mergerdatatype": "C(60)",
                         "Title": "公司注册地",
                         "Description": "公司注册详细地址", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）",
                         "NodeID": 0, "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0, "Mergerunit": "没有单位",
                         "Iscode": 0},
                        {"DownCount": 13897, "Pid": 253, "Fldid": 10499, "Fldname": "Regplc", "Showorder": 20,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 153, "Langid": 0, "Unitid": 0, "Mlangid": 12048, "Kid": 0,
                         "Typename": "Nvarchar", "Length": 50, "Accuracy": 0, "Mergerdatatype": "C(50)",
                         "Title": "公司注册所在地",
                         "Description": "公司注册所在城市", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）",
                         "NodeID": 0, "UnitTitle": "没有单位", "Keytype": 0, "UnitValue": 0, "Mergerunit": "没有单位",
                         "Iscode": 0},
                        {"DownCount": 7318, "Pid": 253, "Fldid": 10500, "Fldname": "Regcap1", "Showorder": 21,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 26, "Langid": 0, "Unitid": 187, "Mlangid": 12049, "Kid": 0,
                         "Typename": "decimal", "Length": 20, "Accuracy": 2, "Mergerdatatype": "N(20,2)",
                         "Title": "公司招股时注册资本",
                         "Description": "股份有限公司的注册资本指实收的股本总额，实收股本总额是指公司股票面值与股份总数的乘积；0：表示以募集发起发行股票的公司其注册资本招股时为0。",
                         "Langtypeid": 1,
                         "TBTitle": "公司基本情况表", "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "元",
                         "Keytype": 0,
                         "UnitValue": 1, "Mergerunit": "元", "Iscode": 0},
                        {"DownCount": 7906, "Pid": 253, "Fldid": 10501, "Fldname": "Regcap2", "Showorder": 22,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 26, "Langid": 0, "Unitid": 187, "Mlangid": 12050, "Kid": 0,
                         "Typename": "decimal", "Length": 20, "Accuracy": 2, "Mergerdatatype": "N(20,2)",
                         "Title": "公司上市时注册资本",
                         "Description": "股份有限公司的注册资本指实收的股本总额，实收股本总额是指公司股票面值与股份总数的乘积。", "Langtypeid": 1,
                         "TBTitle": "公司基本情况表",
                         "Dbid": 45, "DBTitle": "首次公开发行（A股）", "NodeID": 0, "UnitTitle": "元", "Keytype": 0,
                         "UnitValue": 1,
                         "Mergerunit": "元", "Iscode": 0},
                        {"DownCount": 7416, "Pid": 253, "Fldid": 10502, "Fldname": "Nstaff", "Showorder": 23,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 34, "Langid": 0, "Unitid": 105, "Mlangid": 12051, "Kid": 0,
                         "Typename": "decimal", "Length": 8, "Accuracy": 0, "Mergerdatatype": "N(8,0)",
                         "Title": "上市时公司职工人数",
                         "Description": "包括在册的退休人员。", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）",
                         "NodeID": 0, "UnitTitle": "人", "Keytype": 0, "UnitValue": 1, "Mergerunit": "人", "Iscode": 0},
                        {"DownCount": 8061, "Pid": 253, "Fldid": 10503, "Fldname": "Ndrct", "Showorder": 24,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 134, "Langid": 0, "Unitid": 105, "Mlangid": 12052, "Kid": 0,
                         "Typename": "decimal", "Length": 6, "Accuracy": 0, "Mergerdatatype": "N(6,0)",
                         "Title": "上市时公司董事会人数",
                         "Description": "当字段数据为空，说明未披露", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）",
                         "NodeID": 0, "UnitTitle": "人", "Keytype": 0, "UnitValue": 1, "Mergerunit": "人", "Iscode": 0},
                        {"DownCount": 7272, "Pid": 253, "Fldid": 10504, "Fldname": "Nspv", "Showorder": 25,
                         "Replaceid": None,
                         "Tbid": 698, "Datatypeid": 134, "Langid": 0, "Unitid": 105, "Mlangid": 12053, "Kid": 0,
                         "Typename": "decimal", "Length": 6, "Accuracy": 0, "Mergerdatatype": "N(6,0)",
                         "Title": "上市时公司监事会人数",
                         "Description": "当字段数据为空，说明未披露", "Langtypeid": 1, "TBTitle": "公司基本情况表", "Dbid": 45,
                         "DBTitle": "首次公开发行（A股）",
                         "NodeID": 0, "UnitTitle": "人", "Keytype": 0, "UnitValue": 1, "Mergerunit": "人", "Iscode": 0}],
                    "TableName": "IPO_Cobasic",
                    "TableTitle": "公司基本情况表",
                    "CodeKeyField": "Stkcd",
                    "TimeKeyField": "Listdt",
                    "Conditions": [{
                        "FieldName": "Listdt",
                        "Logic": True,
                        "Description": "[Listdt] BETWEEN '" + start_str + "' AND '" + end_str + "'",
                        "Value": start_str + "," + end_str, "Operator": " BETWEEN ",
                        "IsTimeCondition": True, "IsCondition": False
                    }]
                }], "Codes": "", "CodeNames": "", "Institutionids": "",
            "StartTime": start_str, "EndTime": end_str, "DBID": 45, "CodeSelType": "0", "MID": 9,
            "CodeType": "1", "DBTitle": "首次公开发行（A股）", "TreeNodeId": "4313", "QueryString": "?nodeid=253",
            "SingleTableId": 698, "FileFormat": "1", "Ishavetime": True
        }
